export const staticSchool = [
  {
    id: 277,
    name: "Harvard University",
    location: "United States, Massachusetts",
    logo: "https://questapply.com/wp-content/uploads/2022/10/1785_harvard-logo.png",
    ranking: {
      qs: "1",
      usNews: "3",
      forbes: "15",
      shanghai: "1",
      the: "1",
    },
    programs: ["Ph.D: 450 Programs"],
    acceptance: 5,
    graduation: 72,
    cost: {
      inState: 68962,
      outState: 68123,
    },
    favorite: true,
  },
  {
    id: 663,
    name: "Stanford University",
    location: "United States, California",
    logo: "https://questapply.com/wp-content/uploads/2022/10/Stanford_University.png",
    ranking: {
      qs: "2",
      usNews: "3",
      forbes: "2",
      shanghai: "2",
      the: "2",
    },
    programs: ["Ph.D: 644 Programs"],
    acceptance: 5,
    graduation: 60,
    cost: {
      inState: 55011,
      outState: 56169,
    },
    favorite: false,
  },
  {
    id: 398,
    name: "Massachusetts Institute of Technology (MIT)",
    location: "United States, Massachusetts",
    logo: "https://questapply.com/wp-content/uploads/2022/10/Massachusetts_Institute_of_Technology-1.png",
    ranking: {
      qs: "3",
      usNews: "2",
      forbes: "1",
      shanghai: "3",
      the: "3",
    },
    programs: ["Ph.D: 1035 Programs"],
    acceptance: 7,
    graduation: 61,
    cost: {
      inState: 58967,
      outState: 55878,
    },
    favorite: false,
  },
  {
    id: 58,
    name: "University of California, Berkeley",
    location: "United States, California",
    logo: "https://questapply.com/wp-content/uploads/2022/10/University_of_California_Berkeley.png",
    ranking: {
      qs: "4",
      usNews: "20",
      forbes: "3",
      shanghai: "4",
      the: "36",
    },
    programs: ["Ph.D: 752 Programs"],
    acceptance: 17,
    graduation: 27,
    cost: {
      inState: 14160,
      outState: 43980,
    },
    favorite: false,
  },
  {
    id: 771,
    name: "University of California Los Angeles (UCLA)",
    location: "United States, California",
    logo: "https://questapply.com/wp-content/uploads/2022/10/University_of_California_Los_Angeles.png",
    ranking: {
      qs: "5",
      usNews: "20",
      forbes: "6",
      shanghai: "11",
      the: "27",
    },
    programs: ["Ph.D: 658 Programs"],
    acceptance: 14,
    graduation: 29,
    cost: {
      inState: 13036,
      outState: 43012,
    },
    favorite: false,
  },
  {
    id: 1035,
    name: "Yale University",
    location: "United States, Connecticut",
    logo: "https://questapply.com/wp-content/uploads/2022/10/Yale_University.png",
    ranking: {
      qs: "6",
      usNews: "3",
      forbes: "8",
      shanghai: "9",
      the: "4",
    },
    programs: ["Ph.D: 315 Programs"],
    acceptance: 5,
    graduation: 61,
    cost: {
      inState: 45700,
      outState: 59950,
    },
    favorite: false,
  },
  {
    id: 154,
    name: "Columbia University in the City of New York",
    location: "United States, New York",
    logo: "https://questapply.com/wp-content/uploads/2022/10/Columbia_University_in_the_City_of_New_York_170692.png",
    ranking: {
      qs: "7",
      usNews: "18",
      forbes: "5",
      shanghai: "6",
      the: "16",
    },
    programs: ["Ph.D: 585 Programs"],
    acceptance: 4,
    graduation: 73,
    cost: {
      inState: 52924,
      outState: 62466,
    },
    favorite: false,
  },
  {
    id: 552,
    name: "Princeton University",
    location: "United States, New Jersey",
    logo: "https://questapply.com/wp-content/uploads/2022/10/Princeton_University.png",
    ranking: {
      qs: "8",
      usNews: "1",
      forbes: "4",
      shanghai: "5",
      the: "7",
    },
    programs: ["Ph.D: 315 Programs"],
    acceptance: 4,
    graduation: 39,
    cost: {
      inState: 58790,
      outState: 56010,
    },
    favorite: false,
  },
  {
    id: 475,
    name: "New York University",
    location: "United States, New York",
    logo: "https://questapply.com/wp-content/uploads/2022/10/New_York_University.gif",
    ranking: {
      qs: "9",
      usNews: "25",
      forbes: "60",
      shanghai: "17",
      the: "26",
    },
    programs: ["Ph.D: 423 Programs"],
    acceptance: 21,
    graduation: 48,
    cost: {
      inState: 38206,
      outState: 56500,
    },
    favorite: false,
  },
  {
    id: 871,
    name: "University of Pennsylvania",
    location: "United States, Pennsylvania",
    logo: "https://questapply.com/wp-content/uploads/2022/10/University_of_Pennsylvania.gif",
    ranking: {
      qs: "10",
      usNews: "7",
      forbes: "10",
      shanghai: "13",
      the: "12",
    },
    programs: ["Ph.D: 540 Programs"],
    acceptance: 9,
    graduation: 58,
    cost: {
      inState: 42932,
      outState: 61710,
    },
    favorite: false,
  },
];

export const staticPrograms = [
  {
    id: 1073,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "Harvard University",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/1785_harvard-logo.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 1,
    qsRanking: "1",
    deadline: [
      {
        season: "Fall",
        date: "Dec 15",
      },
    ],
    requirements: {
      toefl: {
        min: 92,
        avg: 105,
      },
      ielts: {
        min: 6.5,
        avg: 0,
      },
      duolingo: {
        min: 125,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not accepted",
        total: {
          avg: 329,
        },
        verbal: {
          avg: 161,
        },
        quantitative: {
          avg: 168,
        },
        writing: {
          avg: 4.5,
        },
      },
      gpa: {
        min: 3,
        avg: 3.7,
      },
    },
    costs: {
      residents: {
        tuition: 59,
        fees: 1,
        healthInsurance: 4,
        livingCost: 47301,
      },
      international: {
        tuition: 59,
        fees: 1,
        healthInsurance: 4,
        livingCost: 47301,
      },
    },
    applicationFees: {
      international: 105,
      us: 105,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 4,
    contact: {
      tel: "617-495-5315",
      email: "gsas@fas.harvard.edu",
      website:
        "https://www.seas.harvard.edu/computer-science/graduate-program/general-requirements",
      address: "Harvard University",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: true,
    country: 24,
    state: "Massachusetts",
  },
  {
    id: 5567,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "Stanford University",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/Stanford_University.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 2,
    qsRanking: "2",
    deadline: [
      {
        season: "Fall",
        date: "Dec 5",
      },
    ],
    requirements: {
      toefl: {
        min: 89,
        avg: 111,
      },
      ielts: {
        min: 0,
        avg: 0,
      },
      duolingo: {
        min: 0,
        avg: 0,
      },
      pte: {
        min: 0,
        avg: 0,
      },
      gre: {
        status: "not required",
        total: {
          avg: 333,
        },
        verbal: {
          avg: 165,
        },
        quantitative: {
          avg: 168,
        },
        writing: {
          avg: 4.5,
        },
      },
      gpa: {
        min: 3.5,
        avg: 3.9,
      },
    },
    costs: {
      residents: {
        tuition: 52,
        fees: 964,
        healthInsurance: 6,
        livingCost: 51,
      },
      international: {
        tuition: 52,
        fees: 964,
        healthInsurance: 6,
        livingCost: 51,
      },
    },
    applicationFees: {
      international: 125,
      us: 125,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 8,
    contact: {
      tel: "",
      email: "admissions@cs.stanford.edu",
      website: "https://cs.stanford.edu/academics/phd",
      address: "Stanford University",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "California",
  },
  {
    id: 33467,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "University of California, Berkeley",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/University_of_California_Berkeley.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 4,
    qsRanking: "4",
    deadline: [
      {
        season: "Fall",
        date: "Dec 8",
      },
    ],
    requirements: {
      toefl: {
        min: 90,
        avg: 95,
      },
      ielts: {
        min: 7,
        avg: 0,
      },
      duolingo: {
        min: 115,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not required",
        total: {
          avg: 322,
        },
        verbal: {
          avg: 156,
        },
        quantitative: {
          avg: 166,
        },
        writing: {
          avg: 3.9,
        },
      },
      gpa: {
        min: 3,
        avg: 3.7,
      },
    },
    costs: {
      residents: {
        tuition: 32,
        fees: 212,
        healthInsurance: 3186,
        livingCost: 29450,
      },
      international: {
        tuition: 32,
        fees: 212,
        healthInsurance: 3186,
        livingCost: 29450,
      },
    },
    applicationFees: {
      international: 155,
      us: 135,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 28.4,
    contact: {
      tel: "",
      email: "",
      website: "https://grad.berkeley.edu/program/computer-science/",
      address: "University of California, Berkeley",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "California",
  },
  {
    id: 33468,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "University of California, Berkeley",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/University_of_California_Berkeley.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 4,
    qsRanking: "4",
    deadline: [
      {
        season: "Fall",
        date: "Dec 8",
      },
    ],
    requirements: {
      toefl: {
        min: 90,
        avg: 95,
      },
      ielts: {
        min: 7,
        avg: 0,
      },
      duolingo: {
        min: 115,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not required",
        total: {
          avg: 322,
        },
        verbal: {
          avg: 156,
        },
        quantitative: {
          avg: 166,
        },
        writing: {
          avg: 3.9,
        },
      },
      gpa: {
        min: 3,
        avg: 3.7,
      },
    },
    costs: {
      residents: {
        tuition: 32,
        fees: 212,
        healthInsurance: 3186,
        livingCost: 29450,
      },
      international: {
        tuition: 32,
        fees: 212,
        healthInsurance: 3186,
        livingCost: 29450,
      },
    },
    applicationFees: {
      international: 155,
      us: 135,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 28.4,
    contact: {
      tel: "",
      email: "",
      website: "https://grad.berkeley.edu/program/computer-science/",
      address: "University of California, Berkeley",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "California",
  },
  {
    id: 3341,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "University of California Los Angeles (UCLA)",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/University_of_California_Los_Angeles.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 5,
    qsRanking: "5",
    deadline: [
      {
        season: "Fall",
        date: "Dec 15",
      },
    ],
    requirements: {
      toefl: {
        min: 87,
        avg: 105,
      },
      ielts: {
        min: 7,
        avg: 0,
      },
      duolingo: {
        min: 120,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not required",
        total: {
          avg: 323,
        },
        verbal: {
          avg: 157,
        },
        quantitative: {
          avg: 166,
        },
        writing: {
          avg: 4,
        },
      },
      gpa: {
        min: 3,
        avg: 3.56,
      },
    },
    costs: {
      residents: {
        tuition: 33,
        fees: 1065,
        healthInsurance: 4,
        livingCost: 29,
      },
      international: {
        tuition: 33,
        fees: 1065,
        healthInsurance: 4,
        livingCost: 29,
      },
    },
    applicationFees: {
      international: 155,
      us: 135,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 9,
    contact: {
      tel: "(310) 825-1851",
      email: "ceeapply@seas.ucla.edu",
      website:
        "https://grad.ucla.edu/programs/school-of-engineering-and-applied-science/electrical-computer-engineering/",
      address: "University of California Los Angeles (UCLA)",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "California",
  },
  {
    id: 5541,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "Yale University",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/Yale_University.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 6,
    qsRanking: "6",
    deadline: [
      {
        season: "Fall",
        date: "Dec 15",
      },
    ],
    requirements: {
      toefl: {
        min: 100,
        avg: 105,
      },
      ielts: {
        min: 7.5,
        avg: 0,
      },
      duolingo: {
        min: 120,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not accepted",
        total: {
          avg: 330,
        },
        verbal: {
          avg: 162,
        },
        quantitative: {
          avg: 168,
        },
        writing: {
          avg: 4,
        },
      },
      gpa: {
        min: 3.5,
        avg: 3.7,
      },
    },
    costs: {
      residents: {
        tuition: 46,
        fees: 765,
        healthInsurance: 2,
        livingCost: 36,
      },
      international: {
        tuition: 46,
        fees: 765,
        healthInsurance: 2,
        livingCost: 36,
      },
    },
    applicationFees: {
      international: 80,
      us: 80,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 40.6,
    contact: {
      tel: "203-432-1283",
      email: "rokhlin-vladimir@yale.edu",
      website:
        "https://cpsc.yale.edu/academics/graduate-program/doctor-philosophy",
      address: "Yale University",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "Connecticut",
  },
  {
    id: 5592,
    name: "Computer Engineering",
    degree: "Ph.D.",
    school: "Columbia University in the City of New York",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/Columbia_University_in_the_City_of_New_York_170692.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 7,
    qsRanking: "7",
    deadline: [
      {
        season: "Fall",
        date: "Dec 15",
      },
    ],
    requirements: {
      toefl: {
        min: 99,
        avg: 105,
      },
      ielts: {
        min: 6.5,
        avg: 0,
      },
      duolingo: {
        min: 119,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not required",
        total: {
          avg: 326,
        },
        verbal: {
          avg: 157,
        },
        quantitative: {
          avg: 169,
        },
        writing: {
          avg: 3.9,
        },
      },
      gpa: {
        min: 3,
        avg: 3.7,
      },
    },
    costs: {
      residents: {
        tuition: 2,
        fees: 1092,
        healthInsurance: 3892,
        livingCost: 30827,
      },
      international: {
        tuition: 2,
        fees: 1092,
        healthInsurance: 3892,
        livingCost: 30827,
      },
    },
    applicationFees: {
      international: 150,
      us: 120,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 10,
    contact: {
      tel: "",
      email: "",
      website: "http://bulletin.engineering.columbia.edu/graduate-program-0",
      address: "Columbia University in the City of New York",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "New York",
  },
  {
    id: 597,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "Columbia University in the City of New York",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/Columbia_University_in_the_City_of_New_York_170692.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 7,
    qsRanking: "7",
    deadline: [
      {
        season: "Fall",
        date: "Dec 15",
      },
    ],
    requirements: {
      toefl: {
        min: 99,
        avg: 105,
      },
      ielts: {
        min: 6.5,
        avg: 0,
      },
      duolingo: {
        min: 119,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not required",
        total: {
          avg: 325,
        },
        verbal: {
          avg: 159,
        },
        quantitative: {
          avg: 166,
        },
        writing: {
          avg: 4.3,
        },
      },
      gpa: {
        min: 3,
        avg: 3.7,
      },
    },
    costs: {
      residents: {
        tuition: 2,
        fees: 1092,
        healthInsurance: 3892,
        livingCost: 30827,
      },
      international: {
        tuition: 2,
        fees: 1092,
        healthInsurance: 3892,
        livingCost: 30827,
      },
    },
    applicationFees: {
      international: 150,
      us: 120,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 10,
    contact: {
      tel: "",
      email: " phd-admissions@lists.cs.columbia.edu",
      website: "http://bulletin.engineering.columbia.edu/graduate-programs-4",
      address: "Columbia University in the City of New York",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "New York",
  },
  {
    id: 2193,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "Princeton University",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/Princeton_University.png",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 8,
    qsRanking: "8",
    deadline: [
      {
        season: "Fall",
        date: "Dec 15",
      },
    ],
    requirements: {
      toefl: {
        min: 100,
        avg: 110,
      },
      ielts: {
        min: 7,
        avg: 8,
      },
      duolingo: {
        min: 0,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "not accepted",
        total: {
          avg: 326,
        },
        verbal: {
          avg: 161,
        },
        quantitative: {
          avg: 168,
        },
        writing: {
          avg: 4.6,
        },
      },
      gpa: {
        min: 3.85,
        avg: 3.8,
      },
    },
    costs: {
      residents: {
        tuition: 57,
        fees: 3000,
        healthInsurance: 3,
        livingCost: 34,
      },
      international: {
        tuition: 57,
        fees: 3000,
        healthInsurance: 3,
        livingCost: 34,
      },
    },
    applicationFees: {
      international: 75,
      us: 75,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 40.6,
    contact: {
      tel: "",
      email: "",
      website:
        "https://gradschool.princeton.edu/academics/fields-study/computer-science",
      address: "Princeton University",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "New Jersey",
  },
  {
    id: 1819,
    name: "Computer Science",
    degree: "Ph.D.",
    school: "New York University",
    schoolLogo:
      "https://questapply.com/wp-content/uploads/2022/10/New_York_University.gif",
    degreeType: "Program",
    fit: "Insufficient User Data",
    programType: null,
    duration: "4 Years",
    format: null,
    language: "English",
    campus: "On Campus",
    ranking: 9,
    qsRanking: "9",
    deadline: [
      {
        season: "Fall",
        date: "May 1",
      },
      {
        season: "Winter",
        date: "May 9",
      },
      {
        season: "Spring",
        date: "Jan 14",
      },
    ],
    requirements: {
      toefl: {
        min: 90,
        avg: 100,
      },
      ielts: {
        min: 7,
        avg: 0,
      },
      duolingo: {
        min: 115,
        avg: 0,
      },
      pte: {
        min: 68,
        avg: 0,
      },
      gre: {
        status: "optional",
        total: {
          avg: 316,
        },
        verbal: {
          avg: 152,
        },
        quantitative: {
          avg: 164,
        },
        writing: {
          avg: 3,
        },
      },
      gpa: {
        min: 3,
        avg: 3.3,
      },
    },
    costs: {
      residents: {
        tuition: 38,
        fees: 2706,
        healthInsurance: 1,
        livingCost: 24,
      },
      international: {
        tuition: 38,
        fees: 2706,
        healthInsurance: 1,
        livingCost: 24,
      },
    },
    applicationFees: {
      international: 110,
      us: 110,
    },
    otherRequirements: {
      transcript: true,
      resumeCV: true,
      applicationForm: true,
      statementOfPurpose: true,
      recommendationLetters: 3,
    },
    admissionRate: 25.3,
    contact: {
      tel: "646-997-3204",
      email: "engineering.gradinfo@nyu.edu",
      website:
        "https://engineering.nyu.edu/academics/programs/computer-science-phd",
      address: "New York University",
    },
    description: "",
    courseStructure: "",
    overview: "",
    favorite: false,
    country: 24,
    state: "New York",
  },
];

export const staticProfessors = [
  {
    ID: 479,
    name: "Ran Raz",
    title: "Professor",
    email: "ranr@cs.princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Computational Complexity",
      "Complexity Theory",
      "Communication Complexity",
    ],
    link: "https://engineering.princeton.edu/faculty/ran-raz",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=vmHFZM0AAAAJ&hl=en",
    website: "http://www.wisdom.weizmann.ac.il/~/ranraz/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/raz_ran-450x600_1-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:25.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: true,
  },
  {
    ID: 484,
    name: "Ben Raphael",
    title: "Professor",
    email: "braphael@cs.princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Bioinformatics",
      "Computational Biology",
      "Genomics",
      "Computational Cancer Biology",
    ],
    link: "https://engineering.princeton.edu/faculty/ben-raphael",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=GhvZjJUAAAAJ&hl=en",
    website: "http://compbio.cs.brown.edu/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/ben-raphael_1-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:26.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 482,
    name: "Jennifer Rexford",
    title: "Professor",
    email: "jrex@cs.princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Networking",
      "Computer Networks",
      "Internet Routing",
      "Network Management",
    ],
    link: "https://engineering.princeton.edu/faculty/jennifer-rexford",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=07ds-DAAAAAJ&hl=en",
    website: "http://www.cs.princeton.edu/~jrex/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/rexford_img_3529-450x600_1-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:26.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 480,
    name: "Olga Russakovsky",
    title: "Assistant Professor",
    email: "olgarus@cs.princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Computer vision",
      "Machine Learning",
      "Human Computer Interaction",
      "AI Systems",
    ],
    link: "https://engineering.princeton.edu/faculty/olga-russakovsky",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=TB5OwW8AAAAJ&hl=en",
    website: "http://cs.princeton.edu/~olgarus",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/russakovsky_450x600_0-1.jpg",
    status: "publish",
    creator_id: 13,
    date: "2022-09-08T20:01:26.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 483,
    name: "Szymon Rusinkiewicz",
    title: "Professor",
    email: "smr@Princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Computer Graphics",
      "Computational Fabrication",
      "Computer Vision",
      "Robotics",
    ],
    link: "https://engineering.princeton.edu/faculty/szymon-rusinkiewicz",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=RaScARwAAAAJ&hl=en",
    website: "http://www.cs.princeton.edu/~smr/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/rusinkiewicz_450x600_1-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:26.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 481,
    name: "Yuri Pritykin",
    title: "Assistant Professor",
    email: "pritykin@princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: ["Computational Biology", "Functional Genomics"],
    link: "https://engineering.princeton.edu/faculty/yuri-pritykin",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=Arx56RkJBrYC&hl=en",
    website: "https://pritykinlab.github.io/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/Pritykin-2020-12-crop_450x600-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:26.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 486,
    name: "Arvind Narayanan",
    title: "Associate Professor",
    email: "arvindn@princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Information Privacy",
      "Fairness in Machine Learning",
      "Cryptocurrencies",
      "Tech Policy",
    ],
    link: "https://engineering.princeton.edu/faculty/arvind-narayanan",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=0Bi5CMgAAAAJ&hl=en",
    website: "https://www.cs.princeton.edu/~arvindn/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/narayanan2_450x600_1-1-1568x2091-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:27.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 485,
    name: "Iasonas Petras",
    title: "Professor",
    email: "ipetras@cs.princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Quantum Computation",
      "Information-Based Complexity",
      "Algorithms",
      "Approximation",
    ],
    link: "https://engineering.princeton.edu/faculty/iasonas-petras",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=_ajtFCMAAAAJ&hl=en",
    website: "http://www.cs.princeton.edu/~ipetras/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/petras_450x600_1-1-1568x2091-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:27.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 487,
    name: "Karthik Narasimhan",
    title: "Assistant Professor",
    email: "karthikn@cs.princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: [
      "Natural Language Processing",
      "Reinforcement Learning",
      "Artificial Intelligence",
    ],
    link: "https://engineering.princeton.edu/faculty/karthik-narasimhan",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=euc0GX4AAAAJ&hl=en",
    website: "https://www.cs.princeton.edu/people/profile/karthikn",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/narasimhan_450x600_1-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:27.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
  {
    ID: 488,
    name: "Ravi Netravali",
    title: "Assistant Professor",
    email: "rnetravali@princeton.edu",
    program_id: 7,
    school_id: 552,
    researchInterests: ["Systems", "Networking", "Distributed Systems"],
    link: "https://engineering.princeton.edu/faculty/ravi-netravali",
    department_id: 45,
    google_scholar:
      "https://scholar.google.com/citations?user=4C9naMgAAAAJ&hl=en",
    website: "https://www.cs.princeton.edu/~ravian/",
    linkedin: "",
    image:
      "https://questapply.com/wp-content/uploads/2023/04/netravali_headshot_450x600-1.jpg",
    status: "publish",
    creator_id: 7,
    date: "2022-09-08T20:01:27.000Z",
    program_name: "Computer Science and Engineering, IT& Information",
    area_of_study_name: "Engineering & Technology",
    country_name: "United States of America (USA)",
    school_name: "Princeton University",
    state: "New Jersey",
    country: 24,
    favorite: false,
  },
];
